### PR TITLE
Updated to newest version of NiaPy

### LINKED ISSUE #5: Library problems
Hi @lukapecnik! It seems NiaPy has been updated so "from niapy.algorithms.utility import AlgorithmUtility" (optimization_widget.py) won't work anymore. Please fix it as soon as possible ;)
image
image

I pasted two pictures for you to easier to solve the problem.

best regards!

### PR DESCRIPTION
**Pull request by zStupan**
Fixes #5.

### CODE REVIEW

**Comment by firefly-cpp** [comment]
Nice. Thanks @zStupan.

@lukapecnik, please draft a new release when merged.

**Comment by firefly-cpp** [comment]
@lukapecnik, just a reminder. :)

**Comment by lukapecnik** [comment]
@zStupan thank you for the fix. Please also update the version in the pyproject.toml `NiaPy = "^2.0.0rc12"`. Preferably to the latest release candidate. Thanks 🎉 cc @firefly-cpp

**Comment by zStupan** [comment]
I changed niapy to 2.0.0rc18 in pyproject.toml and updated the lock file with `poetry lock`.

**Pull request merged**
